let worldDescriptor_ED = {
    ajaxEndpoint: "save_report.php",
    sceneTags:        {
        initialSceneId: "prequake_beside_blank",
        secondSceneId:  "postquake_beside_blank",
        black:          "black"
    },
    audioFiles: {
        patient_signout: "./audio/03-active/signout_ed.mp3",
    },
    textBlocks: {
        patient_signout: "<p>So, I’m going to give you some signout.</p> This is Jayden. He is a 2.5kg, 2 week old former 38 week old male infant. He presented to the hospital with fever and we think he has sepsis and shock. He became apneic during his initial evaluation and was intubated and placed on a conventional ventilator.  He is hemodynamically unstable and has received 40mL/kg of saline boluses with another 20mL/kg saline bolus running now.  He was started on a dopamine infusion for continued signs of shock and now has a stable blood pressure. He is receiving antibiotics via an IV as we speak.  He is currently on dextrose containing maintenance IV fluids for some initial hypoglycemia which is now stable. He has received sedation and is minimally responsive.</p><p>  Jayden is currently awaiting a bed in the neonatal intensive care unit. His mother has just stepped out of the unit to make a phone call.</p>",
    },
    requiredObjects:  {
        high:   [
            "postquake_end_code_sheet",
            "pump_antibiotic",
            "pump_dopamine",
            "pump_d10",
            "pump_heparin",
            "pump_saline",
            "postquake_beside_label",
            "postquake_end_gloves",
            "postquake_beside_saline_flush",
            "postquake_end_blankets",
            "postquake_beside_alcohol_wipes",
            "postquake_end_code_sheet_blank",
        ],
        low: [
            "postquake_beside_hat",
            "postquake_beside_penlight",
            "postquake_beside_ivcaps",
            "postquake_beside_roll_of_tape",
            "postquake_end_diapers",
            "postquake_beside_pacifier",
            "postquake_end_baby_wipes",
            "postquake_beside_glucose",
            "postquake_beside_electrolyte",
            "postquake_beside_thermometer",
            "baby_ecg",
            "baby_bp_cuff",
            "baby_clamp",
            "postquake_beside_formula",
        ]
    },
    objects:          {
        postquake_beside_alcohol_wipes: {
            id:            "postquake_beside_alcohol_wipes",
            filename:      "./images/panos/ed/postquake_beside_alcohol_wipes.png",
            label:         "Alcohol Wipes",
            inventory_img: "",
            yaw:           -2.55,
            pitch:         0.714,
            value:         5.09,
        },
        postquake_beside_bottle_nipple: {
            id:            "postquake_beside_bottle_nipple",
            filename:      "./images/panos/ed/postquake_beside_bottle_nipple.png",
            label:         "Bottle Nipple",
            inventory_img: "",
            yaw:           -2.34,
            pitch:         0.560,
            value:         2.5,
        },
        postquake_beside_electrolyte:   {
            id:            "postquake_beside_electrolyte",
            filename:      "./images/panos/ed/postquake_beside_electrolyte.png",
            label:         "Oral Electrolyte Solution",
            inventory_img: "",
            yaw:           -1.93,
            pitch:         0.57,
            value:         2.09,
        },
        postquake_beside_formula:       {
            id:            "postquake_beside_formula",
            filename:      "./images/panos/ed/postquake_beside_formula.png",
            label:         "Formula",
            inventory_img: "",
            yaw:           -2.13,
            pitch:         0.52,
            value:         2.09,
        },
        postquake_beside_glucose:       {
            id:            "postquake_beside_glucose",
            filename:      "./images/panos/ed/postquake_beside_glucose.png",
            label:         "Glucose Water",
            inventory_img: "",
            yaw:           -2.03,
            pitch:         0.53,
            value:         2.41,
        },
        postquake_beside_hat:       {
            id:            "postquake_beside_hat",
            filename:      "./images/panos/ed/postquake_beside_hat.png",
            label:         "Hat",
            inventory_img: "",
            yaw:           2.59,
            pitch:         0.63,
            value:         4.77,
        },
        postquake_beside_ivcaps:        {
            id:            "postquake_beside_ivcaps",
            filename:      "./images/panos/ed/postquake_beside_ivcaps.png",
            label:         "IV Caps",
            inventory_img: "",
            yaw:           -2.31,
            pitch:         0.66,
            value:         3.64,
        },
        postquake_beside_label:  {
            id:            "postquake_beside_label",
            filename:      "./images/panos/ed/postquake_beside_label.png",
            label:         "Label",
            inventory_img: "",
            yaw:           2.39,
            pitch:         0.7,
            value:         6.18,
        },
        postquake_beside_pacifier:      {
            id:            "postquake_beside_pacifier",
            filename:      "./images/panos/ed/postquake_beside_pacifier.png",
            label:         "Pacifier",
            inventory_img: "",
            yaw:           2.58,
            pitch:         0.728,
            value:         2.68,
        },
        postquake_beside_penlight:   {
            id:            "postquake_beside_penlight",
            filename:      "./images/panos/ed/postquake_beside_penlight.png",
            label:         "Penlight",
            inventory_img: "",
            yaw:           -1.99,
            pitch:         0.704,
            value:         4.68,
        },
        postquake_beside_roll_of_tape:  {
            id:            "postquake_beside_roll_of_tape",
            filename:      "./images/panos/ed/postquake_beside_roll_of_tape.png",
            label:         "Roll of Tape",
            inventory_img: "",
            yaw:           -2.48,
            pitch:         0.61,
            value:         4.27,
        },
        postquake_beside_saline_flush:  {
            id:            "postquake_beside_saline_flush",
            filename:      "./images/panos/ed/postquake_beside_saline_flush.png",
            label:         "Saline Flush",
            inventory_img: "",
            yaw:           -2.143,
            pitch:         0.793,
            value:         5.27,
        },
        postquake_beside_saline_vial:    {
            id:            "postquake_beside_saline_vial",
            filename:      "./images/panos/ed/postquake_beside_saline_vial.png",
            label:         "Saline Vial",
            inventory_img: "",
            yaw:           -2.19,
            pitch:         0.65,
            value:         2.5,
        },
        postquake_beside_thermometer:        {
            id:            "postquake_beside_thermometer",
            filename:      "./images/panos/ed/postquake_beside_thermometer.png",
            label:         "Thermometer",
            inventory_img: "",
            yaw:           2.28,
            pitch:         0.51,
            value:         4.55,
        },


        postquake_end_baby_wipes:       {
            id:            "postquake_end_baby_wipes",
            filename:      "./images/panos/ed/postquake_end_baby_wipes.png",
            label:         "Baby Wipes",
            inventory_img: "",
            yaw:           -0.063,
            pitch:         0.531,
            value:         2.5,
        },
        postquake_end_blankets:         {
            id:            "postquake_end_blankets",
            filename:      "./images/panos/ed/postquake_end_blankets.png",
            label:         "Blankets",
            inventory_img: "",
            yaw:           0.279,
            pitch:         0.44,
            value:         5.95,
        },
        postquake_end_box_of_tissues:   {
            id:            "postquake_end_box_of_tissues",
            filename:      "./images/panos/ed/postquake_end_box_of_tissues.png",
            label:         "Box of Tissues",
            inventory_img: "",
            yaw:           0.047,
            pitch:         0.518,
            value:         2.5,
        },
        postquake_end_calculator:       {
            id:            "postquake_end_calculator",
            filename:      "./images/panos/ed/postquake_end_calculator.png",
            label:         "Calculator",
            inventory_img: "",
            yaw:           -2.55,
            pitch:         0.474,
            value:         2.5,
        },
        postquake_end_code_sheet:           {
            id:            "postquake_end_code_sheet",
            filename:      "./images/panos/ed/postquake_end_code_sheet.png",
            label:         "Code Medication Sheet",
            inventory_img: "",
            yaw:           -2.31,
            pitch:         0.403,
            value:         6.55,
        },
        postquake_end_diapers:          {
            id:            "postquake_end_diapers",
            filename:      "./images/panos/ed/postquake_end_diapers.png",
            label:         "Diapers",
            inventory_img: "",
            yaw:           -0.065,
            pitch:         0.436,
            value:         3.09,
        },
        postquake_end_gloves:           {
            id:            "postquake_end_gloves",
            filename:      "./images/panos/ed/postquake_end_gloves.png",
            label:         "Gloves",
            inventory_img: "",
            yaw:           0.388,
            pitch:         0.043,
            value:         5.55,
        },
        postquake_end_hand_sanitizer:   {
            id:            "postquake_end_hand_sanitizer",
            filename:      "./images/panos/ed/postquake_end_hand_sanitizer.png",
            label:         "Hand Sanitizer",
            inventory_img: "",
            yaw:           0.06,
            pitch:         0.42,
            value:         2.5,
        },
        postquake_end_labels:    {
            id:            "postquake_end_labels",
            filename:      "./images/panos/ed/postquake_end_labels.png",
            label:         "Extra Labels",
            inventory_img: "",
            yaw:           -2.82,
            pitch:         0.5,
            value:         2.5,
        },


        prequake_beside_alcohol_wipes:  {
            id:            "prequake_beside_alcohol_wipes",
            filename:      "./images/panos/ed/prequake_beside_alcohol_wipes.png",
            label:         "Alcohol Wipes",
            inventory_img: "",
            yaw:           -1.82,
            pitch:         0.69,
            value:         5.09,
        },
        prequake_end_baby_wipes:        {
            id:            "prequake_end_baby_wipes",
            filename:      "./images/panos/ed/prequake_end_baby_wipes.png",
            label:         "Baby Wipes",
            inventory_img: "",
            yaw:           0.11,
            pitch:         0.53,
            value:         2.5
        },
        prequake_beside_bottle_nipple:     {
            id:            "prequake_beside_bottle_nipple",
            filename:      "./images/panos/ed/prequake_beside_bottle_nipple.png",
            label:         "Bottle Nipple",
            inventory_img: "",
            yaw:           -2.27,
            pitch:         0.576,
            value:         2.5,
        },
        prequake_beside_electrolyte:    {
            id:            "prequake_beside_electrolyte",
            filename:      "./images/panos/ed/prequake_beside_electrolyte.png",
            label:         "Oral Electrolyte Solution",
            inventory_img: "",
            yaw:           -1.94,
            pitch:         0.49,
            value:         2.09,
        },
        prequake_beside_formula:        {
            id:            "prequake_beside_formula",
            filename:      "./images/panos/ed/prequake_beside_formula.png",
            label:         "Formula",
            inventory_img: "",
            yaw:           -2.12,
            pitch:         0.483,
            value:         2.09,
        },
        prequake_beside_glucose:        {
            id:            "prequake_beside_glucose",
            filename:      "./images/panos/ed/prequake_beside_glucose.png",
            label:         "Glucose Water",
            inventory_img: "",
            yaw:           -2.04,
            pitch:         0.48,
            value:         2.41,
        },
        prequake_beside_hat:        {
            id:            "prequake_beside_hat",
            filename:      "./images/panos/ed/prequake_beside_hat.png",
            label:         "Hat",
            inventory_img: "",
            yaw:           2.94,
            pitch:         0.69,
            value:         4.77,
        },
        prequake_beside_ivcaps:         {
            id:            "prequake_beside_ivcaps",
            filename:      "./images/panos/ed/prequake_beside_ivcaps.png",
            label:         "IV Caps",
            inventory_img: "",
            yaw:           -2.06,
            pitch:         0.62,
            value:         3.64,
        },
        prequake_beside_label:   {
            id:            "prequake_beside_label",
            filename:      "./images/panos/ed/prequake_beside_label.png",
            label:         "Label",
            inventory_img: "",
            yaw:           2.48,
            pitch:         0.50,
            value:         6.18,
        },
        prequake_beside_pacifier:       {
            id:            "prequake_beside_pacifier",
            filename:      "./images/panos/ed/prequake_beside_pacifier.png",
            label:         "Pacifier",
            inventory_img: "",
            yaw:           2.59,
            pitch:         0.71,
            value:         2.68,
        },
        prequake_beside_penlight:    {
            id:            "prequake_beside_penlight",
            filename:      "./images/panos/ed/prequake_beside_penlight.png",
            label:         "Penlight",
            inventory_img: "",
            yaw:           -2.19,
            pitch:         0.66,
            value:         4.68
        },
        prequake_beside_roll_of_tape:   {
            id:            "prequake_beside_roll_of_tape",
            filename:      "./images/panos/ed/prequake_beside_roll_of_tape.png",
            label:         "Roll of Tape",
            inventory_img: "",
            yaw:           -2.44,
            pitch:         0.59,
            value:         4.27,
        },
        prequake_beside_saline_flush:   {
            id:            "prequake_beside_saline_flush",
            filename:      "./images/panos/ed/prequake_beside_saline_flush.png",
            label:         "Saline Flush",
            inventory_img: "",
            yaw:           -2.24,
            pitch:         0.77,
            value:         5.27,
        },
        prequake_beside_saline_vial:     {
            id:            "prequake_beside_saline_vial",
            filename:      "./images/panos/ed/prequake_beside_saline_vial.png",
            label:         "Saline Vial",
            inventory_img: "",
            yaw:           -2.40,
            pitch:         0.79,
            value:         2.5,
        },
        prequake_beside_thermometer:         {
            id:            "prequake_beside_thermometer",
            filename:      "./images/panos/ed/prequake_beside_thermometer.png",
            label:         "Thermometer",
            inventory_img: "",
            yaw:           2.30,
            pitch:         0.65,
            value:         2.5,
        },


        prequake_end_blankets:          {
            id:            "prequake_end_blankets",
            filename:      "./images/panos/ed/prequake_end_blankets.png",
            label:         "Blankets",
            inventory_img: "",
            yaw:           0.22,
            pitch:         0.42,
            value:         5.95
        },
        prequake_end_box_of_tissues:    {
            id:            "prequake_end_box_of_tissues",
            filename:      "./images/panos/ed/prequake_end_box_of_tissues.png",
            label:         "Box of Tissues",
            inventory_img: "",
            yaw:           -0.17,
            pitch:         0.53,
            value:         2.5
        },
        prequake_end_calculator:        {
            id:            "prequake_end_calculator",
            filename:      "./images/panos/ed/prequake_end_calculator.png",
            label:         "Calculator",
            inventory_img: "",
            yaw:           -2.582,
            pitch:         0.46,
            value:         2.5,
        },
        prequake_end_code_sheet:            {
            id:            "prequake_end_code_sheet",
            filename:      "./images/panos/ed/prequake_end_code_sheet.png",
            label:         "Code Medication Sheet",
            inventory_img: "",
            yaw:           -2.32,
            pitch:         0.45,
            value:         6.55,
        },
        prequake_end_diapers:           {
            id:            "prequake_end_diapers",
            filename:      "./images/panos/ed/prequake_end_diapers.png",
            label:         "Diapers",
            inventory_img: "",
            yaw:           -0.044,
            pitch:         0.44,
            value:         3.09,
        },
        prequake_end_gloves:            {
            id:            "prequake_end_gloves",
            filename:      "./images/panos/ed/prequake_end_gloves.png",
            label:         "Gloves",
            inventory_img: "",
            yaw:           0.381,
            pitch:         -0.02,
            value:         5.55,
        },
        prequake_end_hand_sanitizer:    {
            id:            "prequake_end_hand_sanitizer",
            filename:      "./images/panos/ed/prequake_end_hand_sanitizer.png",
            label:         "Hand Sanitizer",
            inventory_img: "",
            yaw:           0.092,
            pitch:         0.41,
            value:         2.5,
        },
        prequake_end_labels:     {
            id:            "prequake_end_labels",
            filename:      "./images/panos/ed/prequake_end_labels.png",
            label:         "Extra Labels",
            inventory_img: "",
            yaw:           -2.79,
            pitch:         0.495,
            value:         2.5,
        },
    },
    sceneDescriptors: {
        "prequake_beside_blank":  {
            name:                  "By the bed",
            filename:              "./images/panos/ed/prequake_beside_blank.jpg",
            initialViewParameters: {
                yaw:   -2.8,
                pitch: 0.3,
                fov:   Math.PI / 2
            },
            linkHotspots:          [{
                yaw:        -2.85,
                pitch:      -0.17,
                rotation:   0,
                javascript: "app.stateMachine.enterState(STATE_TRAINING_MODE_END)",
                label:      "End training",
            }, {
                yaw:        2.832,
                pitch:      0.253,
                rotation:   0,
                javascript: "app.stateMachine.enterState(STATE_TRAINING_MODE_PUMP);",
                label:      "Pump",
            },{
                yaw:        2.85,
                pitch:      0.49,
                rotation:   0,
                javascript: "app.stateMachine.enterState(STATE_TRAINING_MODE_BABY);",
                label:      "Baby",
            }],
            teleportHotspots:      [{
                yaw:      1.5415,
                pitch:    0.31,
                rotation: 0,
                target:   "prequake_end_blank",
            }],
            infoHotspots:          [],
            objects:               [
                "prequake_beside_alcohol_wipes",
                "prequake_beside_bottle_nipple",
                "prequake_beside_electrolyte",
                "prequake_beside_formula",
                "prequake_beside_glucose",
                "prequake_beside_ivcaps",
                "prequake_beside_label",
                "prequake_beside_pacifier",
                "prequake_beside_penlight",
                "prequake_beside_roll_of_tape",
                "prequake_beside_saline_flush",
                "prequake_beside_saline_vial",
                "prequake_beside_thermometer",
            ]
        },
        "prequake_end_blank":     {
            name:                  "End of bed",
            filename:              "./images/panos/ed/prequake_end_blank.jpg",
            initialViewParameters: {
                "yaw":   -2.87,
                "pitch": 0.3,
                "fov":   1.5707963267948966
            },
            linkHotspots:          [{
                yaw:        3.05,
                pitch:      0.18,
                rotation:   0,
                javascript: "app.stateMachine.enterState(STATE_ACTIVE_MODE_PUMP);",
                label:      "Pump",
            }],
            teleportHotspots:      [{
                yaw:      -2.60,
                pitch:    0.17,
                rotation: 0,
                target:   "prequake_beside_blank",
            }],
            infoHotspots:          [],
            objects:               [
                "prequake_end_baby_wipes",
                "prequake_end_blankets",
                "prequake_end_box_of_tissues",
                "prequake_end_calculator",
                "prequake_end_code_sheet",
                "prequake_end_diapers",
                "prequake_end_gloves",
                "prequake_end_labels",
                "prequake_end_hand_sanitizer",
            ]
        },
        "postquake_beside_blank": {
            name:                  "By the bed",
            filename:              "./images/panos/ed/postquake_beside_blank.jpg",
            initialViewParameters: {
                yaw:   -2.8,
                pitch: 0.3,
                fov:   1.5707963267948966
            },
            linkHotspots:          [{
                yaw:        -2.85,
                pitch:      -0.17,
                rotation:   0,
                javascript: "app.stateMachine.enterState(STATE_ACTIVE_MODE_END_CHALLENGE)",
                label:      "Assess",
            }, {
                yaw:        2.832,
                pitch:      0.253,
                rotation:   0,
                javascript: "app.stateMachine.enterState(STATE_ACTIVE_MODE_PUMP);",
                label:      "Pump",
            },{
                yaw:        2.85,
                pitch:      0.49,
                rotation:   0,
                javascript: "app.stateMachine.enterState(STATE_ACTIVE_MODE_BABY);",
                label:      "Baby",
            }],
            teleportHotspots:      [{
                yaw:      1.5415,
                pitch:    0.31,
                rotation: 0,
                target:   "postquake_end_blank",
            }],
            infoHotspots:          [],
            objects:               [
                "postquake_beside_alcohol_wipes",
                "postquake_beside_bottle_nipple",
                "postquake_beside_electrolyte",
                "postquake_beside_formula",
                "postquake_beside_glucose",
                "postquake_beside_hat",
                "postquake_beside_ivcaps",
                "postquake_beside_label",
                "postquake_beside_pacifier",
                "postquake_beside_penlight",
                "postquake_beside_roll_of_tape",
                "postquake_beside_saline_flush",
                "postquake_beside_saline_vial",
                "postquake_beside_thermometer",
            ]
        },
        "postquake_end_blank":    {
            name:                  "End of bed",
            filename:              "./images/panos/ed/postquake_end_blank.jpg",
            initialViewParameters: {
                "yaw":   -2.87,
                "pitch": 0.3,
                fov:     1.5707963267948966
            },
            linkHotspots:          [{
                yaw:        3.05,
                pitch:      0.18,
                rotation:   0,
                javascript: "app.stateMachine.enterState(STATE_ACTIVE_MODE_PUMP);",
                label:      "Pump",
            }],
            teleportHotspots:      [{
                yaw:      -2.60,
                pitch:    0.17,
                rotation: 0,
                target:   "postquake_beside_blank",
            }],
            infoHotspots:          [],
            objects:               [
                "postquake_end_baby_wipes",
                "postquake_end_blankets",
                "postquake_end_box_of_tissues",
                "postquake_end_calculator",
                "postquake_end_diapers",
                "postquake_end_code_sheet",
                "postquake_end_gloves",
                "postquake_end_labels",
                "postquake_end_hand_sanitizer",
            ]
        },
        "black":                  {
            name:                  "Black out",
            filename:              "./images/panos/black.png",
            initialViewParameters: {
                pitch: 0,
                yaw:   0,
                fov:   1.5707963267948966
            },
            linkHotspots:          [],
            teleportHotspons:      [],
            infoHotspots:          [],
            objects:               []
        }
    },
    objects2D:        {
        "pump_antibiotic": {
            id:        "pump_antibiotic",
            imageFile: "./images/pump/pump_antibiotic.png",
            label:     "Antibiotic Syringe",
            value:     6.32
        },
        "pump_d10":        {
            id:        "pump_d10",
            imageFile: "./images/pump/pump_d10.png",
            label:     "D10W Infusion",
            value:     6.32
        },
        "pump_dopamine":   {
            id:        "pump_dopamine",
            imageFile: "./images/pump/pump_dopamine.png",
            label:     "Dopamine Syringe",
            value:     6.32
        },
        "pump_heparin":    {
            id:        "pump_heparin",
            imageFile: "./images/pump/pump_heparin.png",
            label:     "Heparin Syringe",
            value:     6.32
        },
        "pump_saline":     {
            id:        "pump_saline",
            imageFile: "./images/pump/pump_saline.png",
            label:     "NS Infusion",
            value:     6.32
        },
        "baby_ambubag":     {
            id:        "baby_ambubag",
            imageFile: "./images/baby/ed/baby_ambubag.png",
            label:     "Ambubag",
            value:     6.87
        },
        "baby_bp_cuff":     {
            id:        "baby_bp_cuff",
            imageFile: "./images/baby/ed/baby_bp_cuff.png",
            label:     "BP Cuff",
            value:     4
        },
        "baby_clamp":     {
            id:        "baby_clamp",
            imageFile: "./images/baby/ed/baby_clamp.png",
            label:     "Replogle Clamp",
            value:     3.23
        },
        "baby_ecg":     {
            id:        "baby_ecg",
            imageFile: "./images/baby/ed/baby_ecg.png",
            label:     "EKG Leads",
            value:     4.27
        },
    },
    scenes2D:         {
        baby: {
            baseImage: "./images/baby/ed/static.jpg",
            width:     726,
            height:    486,
            objects:   [
                "baby_ecg",
                "baby_bp_cuff",
                "baby_clamp",
                "baby_ambubag"
            ]
        },

        pump: {
            baseImage: "./images/pump/static.png",
            width:     726,
            height:    486,
            objects:   [
                "pump_antibiotic",
                "pump_dopamine",
                "pump_d10",
                "pump_heparin",
                "pump_saline",
            ]
        }
    },
    settings:         {},
    viewerOptions:    {
        controls: {
            mouseViewMode: "drag",
            stageType:     'webgl'
        }
    },
    debug: {
        testMode: false,
    }
};